In [8]:
#Load one of the built-in data sets and vectorise
import numpy as np
import pandas as pd
import matplotlib as mpl 
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

#wine = load_wine()
#wine.head()
print(wine.feature_names)
print(wine.target_names)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [9]:
#CREATE DATA FRAME 
wine_df=pd.DataFrame(np.c_[wine['data'],wine['target']],columns=np.append(wine['feature_names'],['target']))


In [10]:
wine['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
wine['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
# Vectorize the Categorical Variables
df = pd.get_dummies(wine_df)
print(df.dtypes)

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target               float64
dtype: object


In [66]:
x= wine_df.drop(['target'], axis=1)
x.head(6)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4

In [67]:
y=wine_df['target']
y.head(6)

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
Name: target, dtype: float64

In [68]:
# splitting into train and test datasets
# 80:20 TRAIN AND TEST
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
#print(x_train)

In [69]:
# Data scaling 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# we fit the train data
scaler.fit(x_train)

# scaling the train and test data
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [70]:
print(x_train)

[[-1.53315972  0.08921567 -1.28760767 -1.32191218]
 [-1.03958718 -1.81405202 -0.25752153 -0.25549563]
 [-1.28637345 -0.14869279 -1.34483468 -1.45521425]
 [ 0.81130987 -0.62450971  0.48642957  0.41101471]
 [-0.29922836 -1.3382351   0.08584051 -0.12219356]
 [-1.53315972  0.80294106 -1.34483468 -1.18861011]
 [ 0.19434419 -2.05196048  0.7153376   0.41101471]
 [ 0.31773733 -1.10032664  1.05869964  0.27771264]
 [ 0.44113046 -0.62450971  0.60088358  0.81092092]
 [ 0.81130987 -0.14869279  1.00147263  0.81092092]
 [-0.7928009   1.04084952 -1.28760767 -1.32191218]
 [-1.16298031 -0.14869279 -1.34483468 -1.32191218]
 [ 0.07095105  0.32712414  0.60088358  0.81092092]
 [-0.17583522 -1.10032664 -0.14306752 -0.25549563]
 [-0.05244208 -0.86241817  0.08584051  0.01110851]
 [-0.17583522 -0.38660125  0.25752153  0.14441057]
 [ 2.29202752  1.75457491  1.68819673  1.34412919]
 [ 0.19434419 -0.86241817  0.7725646   0.54431678]
 [-0.05244208 -0.62450971  0.7725646   1.61073333]
 [ 0.81130987 -0.14869279  0.82

In [88]:
# Training the Model
from sklearn.neural_network import MLPClassifier
# creating an classifier from the model:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=8000)

# let's fit the training data to our model
mlp.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=8000)

In [89]:
from sklearn.metrics import accuracy_score
model1_train = mlp.predict(x_train)
print(accuracy_score(model1_train, y_train))
model1_test = mlp.predict(x_test)
print(accuracy_score(model1_test, y_test))

0.9833333333333333
0.9666666666666667


In [217]:
# Training with different hyperparameters
mlp2 = MLPClassifier(solver='lbfgs', alpha=.25,
                    hidden_layer_sizes=(18, 18), random_state=1)

print(mlp2.fit(x_train, y_train))  

MLPClassifier(alpha=0.25, hidden_layer_sizes=(18, 18), random_state=1,
              solver='lbfgs')


In [218]:
from sklearn.metrics import accuracy_score
model2_train = mlp2.predict(x_train)
print(accuracy_score(model2_train, y_train))
model2_test = mlp2.predict(x_test)
print(accuracy_score(model2_test, y_test))

0.9833333333333333
1.0


In [128]:
# Training model with different hyperparameters
mlp3 = MLPClassifier(hidden_layer_sizes=(28), max_iter=2000, alpha=.25,
                    solver='sgd', verbose=10, tol=.5, random_state=1,
                    learning_rate_init=.001)
print(mlp3.fit(x_train,y_train))

Iteration 1, loss = 0.92954914
Iteration 2, loss = 0.92783880
Iteration 3, loss = 0.92541049
Iteration 4, loss = 0.92234615
Iteration 5, loss = 0.91872141
Iteration 6, loss = 0.91460758
Iteration 7, loss = 0.91007111
Iteration 8, loss = 0.90517277
Iteration 9, loss = 0.89996706
Iteration 10, loss = 0.89450390
Iteration 11, loss = 0.88882446
Iteration 12, loss = 0.88297704
Training loss did not improve more than tol=0.500000 for 10 consecutive epochs. Stopping.
MLPClassifier(alpha=0.25, hidden_layer_sizes=28, max_iter=2000, random_state=1,
              solver='sgd', tol=0.5, verbose=10)


In [129]:
from sklearn.metrics import accuracy_score
model3_train = mlp3.predict(x_train)
print(accuracy_score(model3_train, y_train))
model3_test = mlp3.predict(x_test)
print(accuracy_score(model3_test, y_test))

0.65
0.6333333333333333


In [191]:
# Training model with different hyperparameters
mlp4 = MLPClassifier(hidden_layer_sizes=(30, ),activation='relu', max_iter=5000, alpha=.25,
                    solver='adam', verbose=10, tol=.25, random_state=1,
                    learning_rate_init=.01)
print(mlp4.fit(x_train,y_train))

Iteration 1, loss = 1.24617326
Iteration 2, loss = 1.13029840
Iteration 3, loss = 1.02511688
Iteration 4, loss = 0.93112193
Iteration 5, loss = 0.84874299
Iteration 6, loss = 0.77661861
Iteration 7, loss = 0.71334985
Iteration 8, loss = 0.65645048
Iteration 9, loss = 0.60549756
Iteration 10, loss = 0.56084862
Iteration 11, loss = 0.52220606
Iteration 12, loss = 0.48911707
Training loss did not improve more than tol=0.250000 for 10 consecutive epochs. Stopping.
MLPClassifier(alpha=0.25, hidden_layer_sizes=(30,), learning_rate_init=0.01,
              max_iter=5000, random_state=1, tol=0.25, verbose=10)


In [192]:
from sklearn.metrics import accuracy_score
model4_train = mlp4.predict(x_train)
print(accuracy_score(model4_train, y_train))
model4_test = mlp4.predict(x_test)
print(accuracy_score(model4_test, y_test))

0.85
0.8


In [136]:
# Training sgd with tanh different hyperparameters
mlp5 = MLPClassifier(hidden_layer_sizes=(20, ),activation='tanh', max_iter=5000, alpha=.25,
                    solver='sgd', verbose=10, tol=.25, random_state=1,
                    learning_rate_init=.1)
print(mlp5.fit(x_train,y_train))

Iteration 1, loss = 1.11500664
Iteration 2, loss = 0.76841674
Iteration 3, loss = 0.58757530
Iteration 4, loss = 0.50867225
Iteration 5, loss = 0.46481542
Iteration 6, loss = 0.43434348
Iteration 7, loss = 0.41032906
Iteration 8, loss = 0.39012547
Iteration 9, loss = 0.37245536
Iteration 10, loss = 0.35654747
Iteration 11, loss = 0.34186761
Iteration 12, loss = 0.32802904
Iteration 13, loss = 0.31475508
Training loss did not improve more than tol=0.250000 for 10 consecutive epochs. Stopping.
MLPClassifier(activation='tanh', alpha=0.25, hidden_layer_sizes=(20,),
              learning_rate_init=0.1, max_iter=5000, random_state=1,
              solver='sgd', tol=0.25, verbose=10)


In [137]:
from sklearn.metrics import accuracy_score
model5_train = mlp5.predict(x_train)
print(accuracy_score(model5_train, y_train))
model5_test = mlp5.predict(x_test)
print(accuracy_score(model5_test, y_test))

0.8916666666666667
0.8666666666666667


In [148]:
# Training Adam with Tanh different Hyper Parameters
mlp6 = MLPClassifier(hidden_layer_sizes=(30, ),activation='tanh', max_iter=5000, alpha=.5,
                    solver='adam', verbose=10, tol=.5, random_state=1,
                    learning_rate_init=.001)
print(mlp6.fit(x_train,y_train))

Iteration 1, loss = 1.09914862
Iteration 2, loss = 1.08119864
Iteration 3, loss = 1.06354163
Iteration 4, loss = 1.04618522
Iteration 5, loss = 1.02913643
Iteration 6, loss = 1.01240173
Iteration 7, loss = 0.99598680
Iteration 8, loss = 0.97989664
Iteration 9, loss = 0.96413575
Iteration 10, loss = 0.94870824
Iteration 11, loss = 0.93361771
Iteration 12, loss = 0.91886713
Training loss did not improve more than tol=0.500000 for 10 consecutive epochs. Stopping.
MLPClassifier(activation='tanh', alpha=0.5, hidden_layer_sizes=(30,),
              max_iter=5000, random_state=1, tol=0.5, verbose=10)


In [172]:
from sklearn.metrics import accuracy_score
model6_train = mlp6.predict(x_train)
print(accuracy_score(model6_train, y_train))
model6_test = mlp6.predict(x_test)
print(accuracy_score(model6_test, y_test))

0.6583333333333333
0.5333333333333333


In [181]:
# Training Adam with Identity different Hyper Parameters
mlp7 = MLPClassifier(hidden_layer_sizes=(18, ),activation='identity', max_iter=1000, alpha=.25,
                    solver='adam', verbose=10, tol=.5, random_state=1,
                    learning_rate_init=.001)
print(mlp7.fit(x_train,y_train))

Iteration 1, loss = 0.73612433
Iteration 2, loss = 0.72520004
Iteration 3, loss = 0.71453130
Iteration 4, loss = 0.70412240
Iteration 5, loss = 0.69397585
Iteration 6, loss = 0.68409337
Iteration 7, loss = 0.67447658
Iteration 8, loss = 0.66512648
Iteration 9, loss = 0.65604319
Iteration 10, loss = 0.64722578
Iteration 11, loss = 0.63867235
Iteration 12, loss = 0.63038007
Training loss did not improve more than tol=0.500000 for 10 consecutive epochs. Stopping.
MLPClassifier(activation='identity', alpha=0.25, hidden_layer_sizes=(18,),
              max_iter=1000, random_state=1, tol=0.5, verbose=10)


In [182]:
from sklearn.metrics import accuracy_score
model7_train = mlp7.predict(x_train)
print(accuracy_score(model7_train, y_train))
model7_test = mlp7.predict(x_test)
print(accuracy_score(model7_test, y_test))

0.85
0.8333333333333334
